# Generated by Django 2.2.3 on 2019-07-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=1000)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
