# Generated by Django 2.2.3 on 2019-07-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='date',
        ),
    ]
