# Generated by Django 2.2.3 on 2019-07-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_register_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='published',
        ),
        migrations.AddField(
            model_name='register',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
