# Generated by Django 2.2.3 on 2019-07-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20190725_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='logindata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('date_published', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
